theme: minima
title: Github Pages
author: wmcdonald404  
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      isPost: true
      layout: post
  -
    scope:
      type: recipes
      path: _recipes
    values:
      layout: post

collections:
  recipes:
    output: true      
